# Generated by Django 2.1.3 on 2018-12-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenClothes',
            fields=[
                ('mcid', models.IntegerField(primary_key=True, serialize=False)),
                ('item_url', models.CharField(max_length=500)),
                ('clothes_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=500)),
                ('clothes_detail', models.CharField(max_length=500)),
                ('material', models.CharField(max_length=500)),
                ('accessory1', models.CharField(blank=True, max_length=500)),
                ('accessory2', models.CharField(blank=True, max_length=500)),
                ('accessory3', models.CharField(blank=True, max_length=500)),
                ('accessory4', models.CharField(blank=True, max_length=500)),
                ('accessory5', models.CharField(blank=True, max_length=500)),
                ('accessory6', models.CharField(blank=True, max_length=500)),
                ('accessory7', models.CharField(blank=True, max_length=500)),
                ('accessory8', models.CharField(blank=True, max_length=500)),
                ('accessory9', models.CharField(blank=True, max_length=500)),
                ('accessory10', models.CharField(blank=True, max_length=500)),
                ('accessory11', models.CharField(blank=True, max_length=500)),
                ('accessory12', models.CharField(blank=True, max_length=500)),
                ('accessory13', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WomenClothes',
            fields=[
                ('wcid', models.IntegerField(primary_key=True, serialize=False)),
                ('item_url', models.CharField(max_length=500)),
                ('clothes_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=500)),
                ('clothes_detail', models.CharField(max_length=500)),
                ('material', models.CharField(max_length=500)),
                ('accessory1', models.CharField(blank=True, max_length=500)),
                ('accessory2', models.CharField(blank=True, max_length=500)),
                ('accessory3', models.CharField(blank=True, max_length=500)),
                ('accessory4', models.CharField(blank=True, max_length=500)),
                ('accessory5', models.CharField(blank=True, max_length=500)),
                ('accessory6', models.CharField(blank=True, max_length=500)),
                ('accessory7', models.CharField(blank=True, max_length=500)),
                ('accessory8', models.CharField(blank=True, max_length=500)),
                ('accessory9', models.CharField(blank=True, max_length=500)),
                ('accessory10', models.CharField(blank=True, max_length=500)),
                ('accessory11', models.CharField(blank=True, max_length=500)),
                ('accessory12', models.CharField(blank=True, max_length=500)),
                ('accessory13', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='type',
        ),
        migrations.CreateModel(
            name='MenColor',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.MenClothes')),
                ('color1', models.CharField(blank=True, max_length=7)),
                ('color2', models.CharField(blank=True, max_length=7)),
                ('color3', models.CharField(blank=True, max_length=7)),
                ('color4', models.CharField(blank=True, max_length=7)),
                ('color5', models.CharField(blank=True, max_length=7)),
                ('color6', models.CharField(blank=True, max_length=7)),
                ('color7', models.CharField(blank=True, max_length=7)),
                ('color8', models.CharField(blank=True, max_length=7)),
                ('color9', models.CharField(blank=True, max_length=7)),
                ('color10', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='WomenColor',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.WomenClothes')),
                ('color1', models.CharField(blank=True, max_length=7)),
                ('color2', models.CharField(blank=True, max_length=7)),
                ('color3', models.CharField(blank=True, max_length=7)),
                ('color4', models.CharField(blank=True, max_length=7)),
                ('color5', models.CharField(blank=True, max_length=7)),
                ('color6', models.CharField(blank=True, max_length=7)),
                ('color7', models.CharField(blank=True, max_length=7)),
                ('color8', models.CharField(blank=True, max_length=7)),
                ('color9', models.CharField(blank=True, max_length=7)),
                ('color10', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
