# Generated by Django 2.1.3 on 2018-12-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181205_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mencolor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.MenClothes'),
        ),
        migrations.AlterField(
            model_name='womencolor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.WomenClothes'),
        ),
    ]
