# Generated by Django 2.1.3 on 2018-12-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181205_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mencolor',
            name='color10',
        ),
        migrations.RemoveField(
            model_name='mencolor',
            name='color7',
        ),
        migrations.RemoveField(
            model_name='mencolor',
            name='color8',
        ),
        migrations.RemoveField(
            model_name='mencolor',
            name='color9',
        ),
        migrations.RemoveField(
            model_name='womenclothes',
            name='accessory11',
        ),
        migrations.RemoveField(
            model_name='womenclothes',
            name='accessory12',
        ),
        migrations.RemoveField(
            model_name='womenclothes',
            name='accessory13',
        ),
        migrations.RemoveField(
            model_name='womencolor',
            name='color10',
        ),
        migrations.RemoveField(
            model_name='womencolor',
            name='color7',
        ),
        migrations.RemoveField(
            model_name='womencolor',
            name='color8',
        ),
        migrations.RemoveField(
            model_name='womencolor',
            name='color9',
        ),
    ]
