# Generated by Django 2.1.3 on 2018-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20181206_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenclothes',
            name='accessory11',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='womenclothes',
            name='accessory12',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='womenclothes',
            name='accessory13',
            field=models.CharField(default='', max_length=500),
        ),
    ]
