# Generated by Django 2.1.3 on 2018-12-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
